#
# Basic settings.
#
#url: http://qckanemoto.github.io # or http://you.github.io
url: http://localhost:4000
baseurl: ""
title: Jean-François Fourmond
description: développeur freelance
avatar: /assets/img/icone8.jpg

#
# Icons
#
icons:
  rss: true
  email:
  github: jffourmond
  bitbucket:
  twitter: jf_fourmond
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: https://fr.linkedin.com/in/jffourmond
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-66633059-1
disqus: jffourmond

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Posts récents
str_show_all_posts: Voir tous les posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: false
ogp:
  image_url: http://qckanemoto.github.io/jekyll-qck-theme/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
